### ISSUE TITLE
ummmm

### ISSUE THREAD

**Issue by IShowSpeed-om** [Keytoyze/ManiaRTRender#8]
So it was working just a second ago then thus happens
![Screenshot 2021-09-17 000006](https://user-images.githubusercontent.com/90893275/133738866-02cd690b-8014-47f6-a679-c31a8ea2a05f.png)
i just recently installed this i dont know what caused this.

**Comment by Keytoyze** [comment]
These DLL files have been locked. You can click "Unblock" in the file properties dialog in Windows Explorer. 
Reference: https://stackoverflow.com/questions/8524423/could-not-load-file-or-assembly-hresult-0x80131515-when-adding-controller-to-m/33679426
